GET http://localhost:3000/posts 
Authorization: Bearer 
9bdf58194b2f6dc9de829e0787641e3eccec3f76fb4445d9cca2c021a83c304ebcc262d91f29f2ad9b5d8f5c4983fbd87393ddf21e32d0c3c341bf72cb3d3305
###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/login 
Content-Type: application/json

{
"username": "fahmiihzas"
}